### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ekampp** [mtgrosser/nodo#4]
I'm executing some hashing functions in JS via Nodo from my Ruby code. So far, Nodo is doing everything I want, and my code is working, but I'm getting this warning in stdout:

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit

It [seems](https://stackoverflow.com/questions/49946001/nodejs-maxlistenersexceededwarning) that the default maximum number of event listeners is 10. 

I'm trying to figure out how to proceed from here. I can't seem to access `emitter.setMaxListeners` from within my JS code inside my Nodo class.

Thanks,
Emil

**Comment by mtgrosser** [comment]
You could try

```ruby
class Foo < Nodo::Core
  script 'process.setMaxListeners(100);'
end
```

For code to be run during initialization see [Executing some custom JS during initialization](/mtgrosser/nodo#execute-some-custom-js-during-initialization).

**Comment by ekampp** [comment]
I also did some testing, and you suggestion seems to solve my issue. Thank you very much for your help! 🤝
